server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017
      database: xc_cms
  rabbitmq:
      host: 192.168.25.100
      port: 5672
      username: guest
      password: guest
      virtual-host: /
  freemarker:
    settings:
      template_update_delay: 0
    cache: false #关闭浏览器缓存，方便测试